defaults:
  - override /space@_global_.space: brain_graph
  - override /split@_global_.split: matching
  - _self_

_target_: topofm.data.datasets.brain.BrainDataset.from_disk
dtype: ${dtype}
device: ${device}
space: ${space}
