defaults:
  - _self_
  - model: residual_nn
  - sde: heat_bm
  - data: gaussians_to_moons
  - trainer: default
  - solver: default
  - time_sampler: default
  - ot: default
  - graph: identity
  - hydra: default

run:
  seed: 0
  device: cpu
  dtype: float64
  use_wandb: false
  wandb_project: topofm


