defaults:
  - space: null
  - split: null
  - dataset: null
  - model: null
  - ode: null
  - test: default
  - train: default
  - logger: wandb
  - _self_
  - experiment: ???

coords: spectral

seed: 0
device: mps
dtype: float32
mode: train_and_test

job:
  chdir: true

hydra:
  job_logging:
    root:
      handlers: [file]